<?
namespace uForm\classes\customPHPMailer;

require dirname(__DIR__).'/phpmailer/Exception.php';
require dirname(__DIR__).'/phpmailer/PHPMailer.php';
require dirname(__DIR__).'/phpmailer/SMTP.php';


class PHPMailer extends \PHPMailer\PHPMailer\PHPMailer{
    public function __construct($exceptions = null)
    {
        parent::__construct($exceptions);
        $this->CharSet = 'UTF-8';
    }

    public function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    public function isSMTP()
    {
        parent::isSMTP(); // TODO: Change the autogenerated stub
    }
}

class Exception extends \PHPMailer\PHPMailer\Exception{

}

class SMTP extends \PHPMailer\PHPMailer\SMTP{

}